### PR TITLE
Fix Android USB implementation

### LINKED ISSUE #14: [USB] Remove LinkedList from AndroidUsbDevice
There is no need to use LinkedList. We should use ArrayDeque instead which is faster.

### LINKED ISSUE #16: [USB] Change "open" (boolean) to AtomicBoolean type on AndroidUsbDevice
The Android USB implementation uses a boolean called "open" which is used by more than one thread an can cause concurrency problems. Change its type to AtomicBoolean so we will be sure it won't have any problem during write/reads from different threads.

### PR DESCRIPTION
**Pull request by inm-certi**
Android USB was using the same boolean in two different threads (reported on issue #16).
Also, the LinkedList was replaced by ArrayDeque.

Fix #16
Fix #14

### CODE REVIEW

File: jocd/src/br/org/certi/jocd/dapaccess/connectioninterface/AndroidUsbDevice.java [hunk 1]
```diff
@@ -295,26 +299,36 @@ public void open() {
...
+      this.deviceConnection = null;
+    }
+
+    // Clean endpoints and interface number.
+    this.inputEndpoint = null;
+    this.outputEndpoint = null;
+    this.interfaceNumber = -1;
+
+    // Allow this device to be opened again.
+    this.atomicOpen.set(false);
```
Comment (ghn-certi) [inline jocd/src/br/org/certi/jocd/dapaccess/connectioninterface/AndroidUsbDevice.java]: Shouldn't atomicOpen be checked in the beginning of this function to avoid execution on an already closed connection?

Comment (inm-certi) [reply jocd/src/br/org/certi/jocd/dapaccess/connectioninterface/AndroidUsbDevice.java]: I think this is not necessary because there is no problem to "close" twice - all objects are being checked if is already null, and than set this to false (and at this point, doesn't matter if it was open or not... now it is closed).

In fact, if something goes wrong on "open()" we will call "close()" and clean everything.

Comment (inm-certi) [reply jocd/src/br/org/certi/jocd/dapaccess/connectioninterface/AndroidUsbDevice.java]: @ghn-certi I'll merge this pull request, and if necessary we add a issue for this later.
