### PR TITLE
Remove assert usage from code

### LINKED ISSUE #43: Remove assert
Assert keyword are meant just for debugging.
We should change asserts to "if" and throw exceptions instead.

### PR DESCRIPTION
**Pull request by inm-certi**
Assert in Java are meant just for debugging. This commit remove all assertions changing them to if/throw.

Resolve #43

### CODE REVIEW

File: jocd/src/br/org/certi/jocd/dapaccess/Command.java [hunk 1]
```diff
@@ -310,8 +365,12 @@ public void add(int count, byte request, long[] words, Byte dapIndex) {
    * Decode the response returned by a DAP_TransferBlock
    * CMSIS-DAP command and return it as an array of bytes.
    */
-  private byte[] decodeTransferBlockData(byte[] data) throws TransferError {
-    assert this.getEmpty() == false;
+  private byte[] decodeTransferBlockData(byte[] data) throws TransferError, Error {
+    // Assert this.getEmpty() == false.
+    if (this.getEmpty()) {
+      throw new Error("decodeTransferBlockData: Unexpected getEmpty() value ( " + getEmpty() + ")");
```
Comment (ghn-certi) [inline jocd/src/br/org/certi/jocd/dapaccess/Command.java]: This getEmpty() call could be avoided here, since the error state already occurred and it's already known that the return value will be true.

File: jocd/src/br/org/certi/jocd/dapaccess/Command.java [hunk 2]
```diff
@@ -340,8 +399,12 @@ public void add(int count, byte request, long[] words, Byte dapIndex) {
    * Encode this command into a byte array that can be sent
    * The actual command this is encoded into depends on the data that was added.
    */
-  public byte[] encodeData() {
-    assert this.getEmpty() == false;
+  public byte[] encodeData() throws Error {
+    // Assert this.getEmpty() == false.
+    if (this.getEmpty()) {
+      throw new Error("encodeData: Unexpected getEmpty() value ( " + getEmpty() + ")");
```
Comment (ghn-certi) [inline jocd/src/br/org/certi/jocd/dapaccess/Command.java]: This getEmpty() call could be avoided here, since the error state already occurred and it's already known that the return value will be true.

File: jocd/src/br/org/certi/jocd/dapaccess/Command.java [hunk 3]
```diff
@@ -355,9 +418,17 @@ public void add(int count, byte request, long[] words, Byte dapIndex) {
   /*
    * Decode the response data
    */
-  public byte[] decodeData(byte[] data) throws TransferError {
-    assert this.getEmpty() == false;
-    assert this.dataEncoded == true;
+  public byte[] decodeData(byte[] data) throws TransferError, Error {
+    // Assert this.getEmpty() == false.
+    if (this.getEmpty()) {
+      throw new Error("decodeData: Unexpected getEmpty() value ( " + getEmpty() + ")");
```
Comment (ghn-certi) [inline jocd/src/br/org/certi/jocd/dapaccess/Command.java]: This getEmpty() call could be avoided here, since the error state already occurred and it's already known that the return value will be true.

File: jocd/src/br/org/certi/jocd/dapaccess/Command.java (hunk 1 above)
Comment (inm-certi) [reply jocd/src/br/org/certi/jocd/dapaccess/Command.java]: Fixed on 3905d3fb99c8c6b556bfe3b84b6ed06c2f55747c

File: jocd/src/br/org/certi/jocd/dapaccess/Command.java (hunk 2 above)
Comment (inm-certi) [reply jocd/src/br/org/certi/jocd/dapaccess/Command.java]: Fixed on 3905d3fb99c8c6b556bfe3b84b6ed06c2f55747c

File: jocd/src/br/org/certi/jocd/dapaccess/Command.java (hunk 3 above)
Comment (inm-certi) [reply jocd/src/br/org/certi/jocd/dapaccess/Command.java]: Fixed on 3905d3fb99c8c6b556bfe3b84b6ed06c2f55747c
